### ISSUE TITLE
Script is die? No longer works

### ISSUE THREAD

**Issue by shadowfolder** [thelinuxchoice/instashell#3]
Script can't find password for test account, can you please check script?

**Comment by thelinuxchoice** [comment]
Send screenshot please, i need more info, the script is working.

**Comment by Busaidi77** [comment]
The script couldn't find the password even if you lowered the threads.

**Comment by shadowfolder** [comment]
@Busaidi77 yes! I have the same issue. Maybe ig app hmac has changed...

**Comment by Busaidi77** [comment]
@shadowfolder Maybe,There is something wrong with that script not sure what is it tho....

**Comment by thelinuxchoice** [comment]
@shadowfolder @Busaidi77 the script is working, please send me screeshots. Use 20 threads max.

**Comment by Busaidi77** [comment]
I did 20 threads only and left it for 4 hours i.guess, nothing found. @thelinuxchoice

**Comment by thelinuxchoice** [comment]
@shadowfolder @Busaidi77 Make sure your password is on the wordlist! For the love of God, opening a issue without check this is so noob!

**Comment by shadowfolder** [comment]
@thelinuxchoice  brother i've put my password on first 5 lines in list. Still don't working :( Do you have fresh poc video? Maybe ig has fixed it?

**Comment by phorest0** [comment]
Same issue
`Username account: test
Password List (Enter to default list): 
Threads (Use < 20, Default 10): 20
Username: test
Wordlist: passwords.lst ()
[*] Press Ctrl + C to stop or save session
Pros-MacBook:instashell`

**Comment by silver0321** [comment]
@thelinuxchoice Hello script kiddie, Sorry to insult you directly but you leave me no choice. I know this method will not work with multi-threading well. Only works if you have a very good luck that it does not skip the actual password. Why don't you just close this repo huh??? 

@shadowzoom @ph0rest I think using a single thread will work but not so good right? Because the algorithm was designed to work with single thread execution and not multiple threads. And the @thelinuxchoice why the fuck are you **just killing tor and restarting when you need to change the IP????**, you should actually use the control port to do that. (Copied the solution from AskUbuntu?)

Serious people, @shadowzoom  @ph0rest don't trust this guy... Just don't use these kind of tools!!!
